name: CI
on:
  pull_request:
    branches:
    - develop
jobs:
  tests:
    name: Unit Tests
    runs-on: macOS-latest
    # strategy:
    #   matrix:
    #     destination: ['platform=iOS Simulator,OS=13.1,name=iPhone 8']
        # xcode: ['/Applications/Xcode_11.1.app/Contents/Developer']
    env:
      APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
      APP_STORE_CONNECT_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_KEY_CONTENT }}
      APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
      MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Bundler
        run: bundle install
      - name: Unit Tests
        run: bundle exec fastlane unit_test
      - name: UI Tests
        run: bundle exec fastlane ui_test
